name = "FileToRigidTransform"
uuid = "e6315776-aa1a-4de9-9781-5302fc3234aa"
authors = ["hustf <hustf@users.noreply.github.com>"]
version = "0.1.0"

[deps]
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
WinControllerToFile = "35ccf8fc-7b30-4032-8229-e6f975734ee0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
